name: Free VPS VNC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files
        run: ls -lah

      - name: Setup permissions
        run: chmod +x *.sh

      - name: Run VNC
        run: ./launch_vnc.sh || ./entrypoint.sh
